'''Encryption software by Mr. Vilakshan
That works as the german encryption machine Enigma used in WW-II'''
def encode(txt, code = 27324):
    code %= 100000
    def rotate():
        ab.append(ab[0])
        del(ab[0])
    ab=[" ",'Q','W','E','R','T','Y','U', 'I', 'O', 'P', 'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'Z', 'X', 'C', 'V', 'B', 'N', 'M', 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', 'a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'z', 'x', 'c', 'v', 'b', 'n', 'm', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0']
    space,Q,W,E,R,T,Y,U,I,O,P,A,S,D,F,G,H,J,K,L,Z,X,C,V,B,N,M,q,w,e,r,t1,y,u,i,o,p,a,s,d,f,g,h,j,k,l,z,x,c,v,b,n,m,n1,n2,n3,n4,n5,n6,n7,n8,n9,n0=62,61,60,59,58,57,56,55,54,53,52,51,50,49,48,47,46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0        
    for c_rot in range(code):
        rotate()
    tt=('')
    txt=list(txt)
    for t in txt:
        if(t==" "):
            tt+=ab[space]
        elif(ord(t)==ord('a')):     
            tt+=ab[a]
        elif(ord(t)==ord('b')):
            tt+=ab[b]
        elif(ord(t)==ord('c')):
            tt+=ab[c]
        elif(ord(t)==ord('d')):
            tt+=ab[d]
        elif(ord(t)==ord('e')):
            tt+=ab[e]
        elif(ord(t)==ord('f')):
            tt+=ab[f]
        elif(ord(t)==ord('g')):
            tt+=ab[g]
        elif(ord(t)==ord('h')):
            tt+=ab[h]
        elif(ord(t)==ord('i')):
            tt+=ab[i]
        elif(ord(t)==ord('j')):
            tt+=ab[j]
        elif(ord(t)==ord('k')):
            tt+=ab[k]
        elif(ord(t)==ord('l')):
            tt+=ab[l]
        elif(ord(t)==ord('m')):
            tt+=ab[m]
        elif(ord(t)==ord('n')):
            tt+=ab[n]
        elif(ord(t)==ord('o')):
            tt+=ab[o]
        elif(ord(t)==ord('p')):
            tt+=ab[p]
        elif(ord(t)==ord('q')):
            tt+=ab[q]
        elif(ord(t)==ord('r')):
            tt+=ab[r]
        elif(ord(t)==ord('s')):
            tt+=ab[s]
        elif(ord(t)==ord('t')):
            tt+=ab[t1]
        elif(ord(t)==ord('u')):
            tt+=ab[u]
        elif(ord(t)==ord('v')):
            tt+=ab[v]
        elif(ord(t)==ord('w')):
            tt+=ab[w]
        elif(ord(t)==ord('x')):
            tt+=ab[x]
        elif(ord(t)==ord('y')):
            tt+=ab[y]
        elif(ord(t)==ord('z')):
            tt+=ab[z]
        elif(ord(t)==ord('A')):
            tt+=ab[A]
        elif(ord(t)==ord('B')):
            tt+=ab[B]
        elif(ord(t)==ord('C')):
            tt+=ab[C]
        elif(ord(t)==ord('D')):
            tt+=ab[D]
        elif(ord(t)==ord('E')):
            tt+=ab[E]
        elif(ord(t)==ord('F')):
            tt+=ab[F]
        elif(ord(t)==ord('G')):
            tt+=ab[G]
        elif(ord(t)==ord('H')):
            tt+=ab[H]
        elif(ord(t)==ord('I')):
            tt+=ab[I]
        elif(ord(t)==ord('J')):
            tt+=ab[J]
        elif(ord(t)==ord('K')):
            tt+=ab[K]
        elif(ord(t)==ord('L')):
            tt+=ab[L]
        elif(ord(t)==ord('M')):
            tt+=ab[M]
        elif(ord(t)==ord('N')):
            tt+=ab[N]
        elif(ord(t)==ord('O')):
            tt+=ab[O]
        elif(ord(t)==ord('P')):
            tt+=ab[P]
        elif(ord(t)==ord('Q')):
            tt+=ab[Q]
        elif(ord(t)==ord('R')):
            tt+=ab[R]
        elif(ord(t)==ord('S')):
            tt+=ab[S]
        elif(ord(t)==ord('T')):
            tt+=ab[T]
        elif(ord(t)==ord('U')):
            tt+=ab[U]
        elif(ord(t)==ord('V')):
            tt+=ab[V]
        elif(ord(t)==ord('W')):
            tt+=ab[W]
        elif(ord(t)==ord('X')):
            tt+=ab[X]
        elif(ord(t)==ord('Y')):
            tt+=ab[Y]
        elif(ord(t)==ord('Z')):
            tt+=ab[Z]
        elif(ord(t)==ord('1')):
            tt+=ab[n1]
        elif(ord(t)==ord('2')):
            tt+=ab[n2]
        elif(ord(t)==ord('3')):
            tt+=ab[n3]
        elif(ord(t)==ord('4')):
            tt+=ab[n4]
        elif(ord(t)==ord('5')):
            tt+=ab[n5]
        elif(ord(t)==ord('6')):
            tt+=ab[n6]
        elif(ord(t)==ord('7')):
            tt+=ab[n7]
        elif(ord(t)==ord('8')):
            tt+=ab[n8]
        elif(ord(t)==ord('9')):
            tt+=ab[n9]
        elif(ord(t)==ord('0')):
            tt+=ab[n0]
        else:
            tt+=t
        rotate()
    return tt

